// generated by stringer -type=RuleStatusType -type=RuleStateType rule.go; DO NOT EDIT

package main

import "fmt"

const _RuleStateType_name = "RuleStateUnknownRuleStateSuccessRuleStateFail"

var _RuleStateType_index = [...]uint8{0, 16, 32, 45}

func (i RuleStateType) String() string {
	if i < 0 || i >= RuleStateType(len(_RuleStateType_index)-1) {
		return fmt.Sprintf("RuleStateType(%d)", i)
	}
	return _RuleStateType_name[_RuleStateType_index[i]:_RuleStateType_index[i+1]]
}
