// generated by stringer -type=RuleStatusType rule.go; DO NOT EDIT

package main

import "fmt"

const _RuleStatusType_name = "RuleStatusUnsetRuleStatusEnabledRuleStatusDisabledRuleStatusAlwaysFailRuleStatusAlwaysSuccess"

var _RuleStatusType_index = [...]uint8{0, 15, 32, 50, 70, 93}

func (i RuleStatusType) String() string {
	if i < 0 || i >= RuleStatusType(len(_RuleStatusType_index)-1) {
		return fmt.Sprintf("RuleStatusType(%d)", i)
	}
	return _RuleStatusType_name[_RuleStatusType_index[i]:_RuleStatusType_index[i+1]]
}
